version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: accounts_transactions
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5500:5432"

  server:
    build: .
    command: python src/server.py
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db/accounts_transactions
    ports:
      - "8000:8000"
    volumes:
      - .:/codef

volumes:
  postgres_data:
